services:
  simple_postgres:
    image: postgres:14.1-alpine
    container_name: fast_api_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: fast-api
    ports:
      - 5432:5432
    volumes:
      - simple_postgres_data:/var/lib/postgresql/data
    networks:
      - fast-api-network

networks:
  fast-api-network:
    driver: bridge

volumes:
  simple_postgres_data: